# Generated by Django 4.2.21 on 2025-05-14 20:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("gocabapp", "0003_rider_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Driver",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=255)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=15, null=True, unique=True),
                ),
                ("date_of_birth", models.DateField()),
                ("vehicle_type", models.CharField(max_length=50)),
                ("vehicle_model", models.CharField(max_length=100)),
                (
                    "drivers_license",
                    models.FileField(upload_to="documents/drivers_license/"),
                ),
                (
                    "vehicle_insurance",
                    models.FileField(upload_to="documents/vehicle_insurance/"),
                ),
                (
                    "vehicle_registration",
                    models.FileField(upload_to="documents/vehicle_registration/"),
                ),
                (
                    "roadworthiness_certificate",
                    models.FileField(upload_to="documents/roadworthiness_certificate/"),
                ),
                ("national_identification_number", models.CharField(max_length=100)),
                (
                    "proof_of_residency",
                    models.FileField(upload_to="documents/proof_of_residency/"),
                ),
                (
                    "passport_photo",
                    models.FileField(upload_to="documents/passport_photos/"),
                ),
                ("bank_name", models.CharField(max_length=100)),
                ("account_number", models.CharField(max_length=20)),
                ("account_holder_name", models.CharField(max_length=255)),
                ("is_approved", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
