# Generated by Django 4.2.21 on 2025-05-15 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gocabapp", "0004_driver"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rider",
            name="password",
        ),
        migrations.AlterField(
            model_name="driver",
            name="account_number",
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="driver",
            name="phone_number",
            field=models.CharField(blank=True, max_length=11, null=True, unique=True),
        ),
    ]
