# Generated by Django 4.2.21 on 2025-05-22 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gocabapp", "0006_userprofile_trip_riderequest_notification_fare"),
    ]

    operations = [
        migrations.RenameField(
            model_name="riderequest",
            old_name="dropoff_location",
            new_name="current_location",
        ),
        migrations.RenameField(
            model_name="riderequest",
            old_name="pickup_location",
            new_name="destination",
        ),
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
