# Generated by Django 4.2.21 on 2025-05-22 18:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "gocabapp",
            "0007_rename_dropoff_location_riderequest_current_location_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trip",
            name="driver",
        ),
        migrations.AddField(
            model_name="riderequest",
            name="driver",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ride_requests_as_driver",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
