# Generated by Django 4.2.21 on 2025-05-22 18:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("gocabapp", "0008_remove_trip_driver_riderequest_driver"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="driver",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="trips_as_driver",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
