# Generated by Django 4.2.21 on 2025-06-02 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gocabapp", "0010_riderequest_completed_at_riderequest_started_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="riderequest",
            name="base_fare",
            field=models.DecimalField(decimal_places=2, default=500.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="riderequest",
            name="distance_fare",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="riderequest",
            name="distance_km",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="riderequest",
            name="duration_min",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="riderequest",
            name="surge_multiplier",
            field=models.DecimalField(decimal_places=1, default=1.0, max_digits=3),
        ),
        migrations.AddField(
            model_name="riderequest",
            name="time_fare",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="riderequest",
            name="total_fare",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
