# Generated by Django 4.2.21 on 2025-06-03 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gocabapp", "0011_riderequest_base_fare_riderequest_distance_fare_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="driver",
            name="rating",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
