# Generated by Django 4.2.21 on 2025-06-03 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gocabapp", "0012_driver_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="driver",
            name="license_plate",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
