# Generated by Django 4.2.23 on 2025-07-31 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gocabapp", "0013_driver_license_plate"),
    ]

    operations = [
        migrations.AddField(
            model_name="rider",
            name="address",
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
