# Generated by Django 4.2.23 on 2025-10-19 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gocabapp", "0015_remove_notification_is_read_notification_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="driver",
            name="current_address",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="driver",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="driver",
            name="location_updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="driver",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
