# Generated by Django 4.2.23 on 2025-10-22 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gocabapp", "0017_riderequest_paid_at_riderequest_payment_reference_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="riderequest",
            name="dropoff_latitude",
        ),
        migrations.RemoveField(
            model_name="riderequest",
            name="dropoff_longitude",
        ),
        migrations.AddField(
            model_name="riderequest",
            name="destination_latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="riderequest",
            name="destination_longitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="riderequest",
            name="pickup_latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="riderequest",
            name="pickup_longitude",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
