# Generated by Django 4.2.25 on 2025-10-26 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("gocabapp", "0018_remove_riderequest_dropoff_latitude_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="driver",
            name="current_ride",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="active_driver",
                to="gocabapp.riderequest",
            ),
        ),
        migrations.AddField(
            model_name="driver",
            name="is_busy",
            field=models.BooleanField(default=False),
        ),
    ]
