# Generated by Django 4.2.26 on 2025-11-09 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gocabapp", "0019_driver_current_ride_driver_is_busy"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rider",
            name="address",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
