# Generated by Django 4.2.26 on 2025-11-09 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gocabapp", "0020_alter_rider_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rider",
            name="address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
