# Generated by Django 4.2.30 on 2026-08-16 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gocabapp", "0021_alter_rider_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="driver",
            name="phone_number",
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
