# Generated by Django 4.2.30 on 2026-09-10 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gocabapp", "0022_alter_driver_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="driver",
            name="is_online",
            field=models.BooleanField(default=False),
        ),
    ]
