# Generated by Django 4.2.30 on 2026-09-11 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gocabapp", "0023_driver_is_online"),
    ]

    operations = [
        migrations.AddField(
            model_name="riderequest",
            name="cash_confirmation_attempts",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="riderequest",
            name="cash_confirmation_code",
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name="riderequest",
            name="payment_method",
            field=models.CharField(
                choices=[("online", "Online"), ("cash", "Cash")],
                default="online",
                max_length=10,
            ),
        ),
    ]
