# Generated by Django 4.2.30 on 2026-09-11 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gocabapp", "0025_drivercancellation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="riderequest",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("paid", "Paid"),
                    ("failed", "Failed"),
                    ("refunded", "Refunded"),
                    ("disputed", "Disputed — driver reported non-payment"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
    ]
