# Generated by Django 4.2.30 on 2026-09-12 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gocabapp", "0027_paymentdispute"),
    ]

    operations = [
        migrations.AddField(
            model_name="rider",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="rider",
            name="location_updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="rider",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
