# Generated by Django 4.2.30 on 2026-09-12 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gocabapp", "0028_rider_latitude_rider_location_updated_at_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="riderequest",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ["pending", "accepted", "started"])),
                fields=("passenger",),
                name="one_active_ride_per_rider",
            ),
        ),
    ]
