# Generated by Django 4.2.30 on 2026-09-12 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("gocabapp", "0030_rider_rating_rating_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="driverpayout",
            name="ride",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="gocabapp.riderequest"
            ),
        ),
    ]
