# Generated by Django 4.2.30 on 2026-09-12 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("gocabapp", "0031_alter_driverpayout_ride"),
    ]

    operations = [
        migrations.AddField(
            model_name="driver",
            name="cash_debt",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name="CashDebtEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "entry_type",
                    models.CharField(
                        choices=[("charge", "Charge"), ("settlement", "Settlement")],
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("note", models.CharField(blank=True, default="", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cash_debt_entries",
                        to="gocabapp.driver",
                    ),
                ),
                (
                    "ride",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gocabapp.riderequest",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="cashdebtentry",
            constraint=models.UniqueConstraint(
                condition=models.Q(("entry_type", "charge")),
                fields=("ride",),
                name="one_cash_debt_charge_per_ride",
            ),
        ),
    ]
