# Generated by Django 4.2.30 on 2026-09-15 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gocabapp", "0032_driver_cash_debt_cashdebtentry_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="driver",
            name="proof_of_residency",
        ),
        migrations.RemoveField(
            model_name="driver",
            name="roadworthiness_certificate",
        ),
        migrations.RemoveField(
            model_name="driver",
            name="vehicle_insurance",
        ),
        migrations.RemoveField(
            model_name="driver",
            name="vehicle_registration",
        ),
        migrations.AddField(
            model_name="driver",
            name="nin_slip_photo",
            field=models.FileField(
                blank=True, default="", upload_to="documents/nin_slips/"
            ),
        ),
        migrations.AddField(
            model_name="driver",
            name="production_year",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="driver",
            name="vehicle_brand",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="driver",
            name="vehicle_color",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="driver",
            name="vehicle_picture",
            field=models.FileField(
                blank=True, default="", upload_to="documents/vehicle_pictures/"
            ),
        ),
        migrations.AlterField(
            model_name="driver",
            name="vehicle_model",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
