# Generated by Django 4.2.30 on 2026-09-15 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gocabapp", "0033_remove_driver_proof_of_residency_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="driver",
            name="needs_reverification",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="driver",
            name="rejection_reason",
            field=models.TextField(blank=True, default=""),
        ),
    ]
