# Generated by Django 4.2.30 on 2026-09-15 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gocabapp", "0034_driver_needs_reverification_driver_rejection_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="riderequest",
            name="recipient_phone_number",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
    ]
