# Generated by Django 4.2.30 on 2026-09-15 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gocabapp', '0035_riderequest_recipient_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='paystack_bank_code',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='driver',
            name='paystack_recipient_code',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
