# Generated by Django 4.2.30 on 2026-09-16 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gocabapp', '0036_driver_paystack_bank_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riderequest',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('reported', 'Reported — awaiting admin review'), ('disputed', 'Disputed — flagged by admin')], default='pending', max_length=10),
        ),
    ]
