# Generated by Django 4.2.30 on 2026-09-16 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gocabapp', '0037_alter_riderequest_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='flagged_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='driver',
            name='is_flagged',
            field=models.BooleanField(default=False),
        ),
    ]
