# Generated by Django 4.2.30 on 2026-09-18 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gocabapp', '0039_ridemessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdispute',
            name='driver_responded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
