# Generated by Django 4.2.30 on 2026-09-19 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gocabapp', '0041_devicetoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderequest',
            name='stale_alert_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
