# Generated by Django 4.2.30 on 2026-09-19 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gocabapp', '0042_riderequest_stale_alert_sent_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='riderequest',
            name='stale_alert_sent_at',
        ),
        migrations.AddField(
            model_name='riderequest',
            name='pending_alert_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='riderequest',
            name='started_alert_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
