# Generated by Django 4.2.30 on 2026-09-21 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gocabapp', '0043_remove_riderequest_stale_alert_sent_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderequest',
            name='unpaid_reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
