# Generated by Django 4.2.30 on 2026-09-22 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gocabapp', '0045_unique_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='national_identification_number',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
