# Generated by Django 4.2.30 on 2026-09-23 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gocabapp', '0047_weekly_payout_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='rider',
            name='flagged_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='rider',
            name='is_flagged',
            field=models.BooleanField(default=False),
        ),
    ]
