# Generated by Django 4.2.30 on 2026-09-26 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gocabapp', '0048_rider_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='drivers_license',
            field=models.FileField(max_length=255, upload_to='documents/drivers_license/'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='nin_slip_photo',
            field=models.FileField(blank=True, default='', max_length=255, upload_to='documents/nin_slips/'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='passport_photo',
            field=models.FileField(max_length=255, upload_to='documents/passport_photos/'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='vehicle_picture',
            field=models.FileField(blank=True, default='', max_length=255, upload_to='documents/vehicle_pictures/'),
        ),
    ]
