# Generated by Django 4.2.30 on 2026-09-26 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gocabapp', '0049_driver_file_field_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='account_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AddConstraint(
            model_name='driver',
            constraint=models.UniqueConstraint(fields=('bank_name', 'account_number'), name='unique_bank_account_number'),
        ),
    ]
