# Generated by Django 4.2.30 on 2026-09-27 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("gocabapp", "0051_support_worker_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="rider",
            name="referral_code",
            field=models.CharField(blank=True, max_length=8, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="rider",
            name="referral_reward_credited",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="rider",
            name="referred_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="referrals",
                to="gocabapp.rider",
            ),
        ),
        migrations.AddField(
            model_name="rider",
            name="wallet_credit_balance",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="riderequest",
            name="wallet_credit_applied",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
