# Generated by Django 4.2.30 on 2026-09-30 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gocabapp", "0053_backfill_referral_codes"),
    ]

    operations = [
        migrations.AddField(
            model_name="riderequest",
            name="vehicle_type",
            field=models.CharField(
                choices=[("Bike", "Bike"), ("Bicycle", "Bicycle")],
                default="Bike",
                max_length=10,
            ),
        ),
    ]
