# Generated by Django 4.2.30 on 2026-10-01 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gocabapp", "0054_ride_vehicle_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="riderequest",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("paid", "Paid"),
                    ("failed", "Failed"),
                    ("refunded", "Refunded"),
                    ("reported", "Reported, awaiting admin review"),
                    ("disputed", "Disputed, flagged by admin"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
    ]
