# Generated by Django 4.2.30 on 2026-10-02 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gocabapp", "0055_fix_payment_status_choice_labels"),
    ]

    operations = [
        migrations.AddField(
            model_name="weeklypayoutbatch",
            name="cashout_fee",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
