# Generated by Django 4.2.30 on 2026-10-02 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gocabapp", "0056_weekly_payout_batch_cashout_fee"),
    ]

    operations = [
        migrations.AddField(
            model_name="riderequest",
            name="arrival_notified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
